version: '3.8'

services:
  db_postgres:
    image: postgres:16-alpine
    container_name: todolist-db-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todolist-network
  backend:
    build:
      context: ./backend/todolist
    container_name: todolist-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db_postgres
    networks:
      - todolist-network

#  frontend:
#    build:
#      context: ./frontend
#    container_name: todolist-frontend
#    restart: always
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend
#    networks:
#      - todolist-network

volumes:
  postgres_data:

networks:
  todolist-network:
    driver: bridge